---
namespace: namespace_example
name: collection_example
readme: README.md
authors:
  - Alejandro de la Hoz <adelahoz@redhat.com>
description: Example modules
license:
  - GPL-2.0-or-later
license_file: ''
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
version: 1.0.2
tags:
  - linux
build_ignore:
  - .gitignore
  - tests/output
  - '**/__pycache__'
  - '**/*.pyc'
  - ansible-navigator.log
  - playbooks/prueba.txt
  - roles/get_server_example_role/tests/prueba.txt
